### PR TITLE
Use parametric type for `region` field

### PR DESCRIPTION
**Pull request by jipolanco**
I was wondering if there's any reason for the `region` field of the FFTWPlan types to be `Any`.

This PR sets `region` to a concrete (parametric) type. Tests pass, at least on my machine with Julia 1.3.0-rc3.

Feel free to ignore this if there's something I'm missing.

### CODE REVIEW

**Comment by mcabbott** [comment]
Ideally this would extend up to the types in https://github.com/JuliaMath/AbstractFFTs.jl, `abstract type Plan{T,R} end`.

**Comment by stevengj** [comment]
It's not clear that the abstract `Plan` needs this, since there are no abstract `Plan` methods that use the region info.

**Comment by stevengj** [comment]
LGTM.

**Comment by mcabbott** [comment]
My reason to want it in the AbstractFFTs type is that it would enable other packages, which depend only on that one, to rely on this information. (My original example involved NamedDims.jl.)

**Pull request merged**
