### PR TITLE
fix mistypo

### LINKED ISSUE #59: Typo in a `plan_inv` method
Reported by @appleparan in https://github.com/JuliaLang/julia/issues/25598:
https://github.com/JuliaMath/FFTW.jl/blob/6e26a1ee12c5f05a9c8eb5f653b56f04ab568b80/src/fft.jl#L700

### PR DESCRIPTION
**Pull request by appleparan**
fix #59

### CODE REVIEW

**Comment by martinholters** [comment]
As this bug went undiscovered for so long, apparently the affected method is not covered by any tests - this might be a good opportunity to change that.

**Comment by appleparan** [comment]
waiting for JuliaMath/AbstractFFTs.jl#10 to be merged. After that I will add tests.

**Comment by martinholters** [comment]
Bump. I think the time is ripe to rebase this and add tests.

**Comment by appleparan** [comment]
ok I will add tests.

Liam Jongsu Kim

**Comment by appleparan** [comment]
We already have a test about `plan_rfft` on [this line](https://github.com/JuliaMath/FFTW.jl/blob/master/test/runtests.jl#L187), and when I used same syntax to use `rfft` and `irfft`, it works, obviously.

However, I'm taking another approach from test. As document[https://juliamath.github.io/AbstractFFTs.jl/stable/api.html#AbstractFFTs.plan_fft] says, when I tested with "preallocated array" , Tests using "preallocated array" fails due to mistypo. However, even if I tested with fixed code, it failed because Julia says it doesn't have proper method for `ldiv!` on [AbstractFFTs](https://github.com/JuliaMath/AbstractFFTs.jl/blob/master/src/definitions.jl#L228) 
The followings are my code snippet and questions. I'm still looking for better solution for this. 

My simplified test snippet is here 
```
using LinearAlgebra
using AbstractFFTs
using FFTW
using Random
using Test

n = 5
srand()
a_r1 = rand(n, n)
a_c1 = rfft(a_r1)
a_r2 = irfft(a_c1, n)

@test isapprox(a_r1, a_r2)

pr = plan_rfft(a_r1)
pir = plan_irfft(a_c1, n)

a_r1 = rand(n, n)
a_c1 = pr * a_r1
a_r2 = pir * a_c1
@test isapprox(a_r1, a_r2)

a_c1 = zeros(ComplexF64, (div(n, 2) + 1, n))
a_r2 = zeros((n, n))
# same as a_c1 = pr * a_r1
mul!(a_c1, pr, a_r1)
# same as a_r2 = pir * a_c1
ldiv!(a_c1, pir, a_r2)
@test isapprox(a_r1, a_r2)
```

and StackTrace 
```

Stacktrace:
 [1] mul!(::Array{Float64,2}, ::AbstractFFTs.ScaledPlan{Float64,FFTW.rFFTWPlan{Float64,-1,false,2},Float64}, ::Array{Complex{Float64},2}) at /home/buildworker/.
/AbstractFFTs/src/definitions.jl:276
 [2] ldiv!(::Array{Float64,2}, ::AbstractFFTs.ScaledPlan{Complex{Float64},FFTW.rFFTWPlan{Complex{Float64},1,false,2},Float64}, ::Array{Complex{Float64},2}) at /
worker/.julia/v0.7/AbstractFFTs/src/definitions.jl:228
 [3] top-level scope
 [4] include at ./boot.jl:306 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1072
 [6] include(::Module, ::String) at ./sysimg.jl:29
 [7] exec_options(::Base.JLOptions) at ./client.jl:327
 [8] _start() at ./client.jl:455
```

My question is 
1. Why original test code pass? How it doesn't use  [Line 187](https://github.com/JuliaMath/FFTW.jl/blob/master/test/runtests.jl#L187) of `runtests.jl`?

2. Why `ldiv!` is missing on `AbstractFFTs`?
  
    1. `ldiv!` is actually same as `mul!` (internally, `lmul!`) [Line 228](https://github.com/JuliaMath/AbstractFFTs.jl/blob/master/src/definitions.jl#L228)

    ```
        LinearAlgebra.ldiv!(y::AbstractArray, p::Plan, x::AbstractArray) = LinearAlgebra.mul!(y, inv(p), x)
    ```

    2. `mul!` probably accepts `ScaledPlan` type due to following two codes. [Line 222](https://github.com/JuliaMath/AbstractFFTs.jl/blob/master/src/definitions.jl#L222) and [Line 273](https://github.com/JuliaMath/AbstractFFTs.jl/blob/master/src/definitions.jl#L273)
    ```
        _pinv_type(p::Plan) = typeof([plan_inv(x) for x in typeof(p)[]])
        pinv_type(p::Plan) = eltype(_pinv_type(p))
    ```
    ```
        plan_inv(p::ScaledPlan) = ScaledPlan(plan_inv(p.p), inv(p.scale))
    ```

PS : I don't think `rfft` test should be in [loops](https://github.com/JuliaMath/FFTW.jl/blob/master/test/runtests.jl#L75) . The loop is for complex FFTs and it makes slow test due to duplication.

If we could change [some test code](https://github.com/JuliaMath/FFTW.jl/blob/master/test/runtests.jl#L234), 
```
@test size(rfftd3_m3d) == size(fftd3_m3d)
```
to 
```
@test size(rfftd3_m3d) == size(true_fftd3_m3d)
```
we could help the `rfft` test get out of the loop

**Comment by appleparan** [comment]
Is it okay to be merged? @ararslan

**Pull request merged**
