### PR TITLE
nthreads check should be outside of static if

### PR DESCRIPTION
**Pull request by stevengj**
This line looks suspicious to me — seems like this needs to be a runtime check, not in `@static if`.

### CODE REVIEW

**Comment by ararslan** [comment]
Can `nthreads` be configured at runtime? I thought it was only set at startup.

**Comment by stevengj** [comment]
It's only at startup, but doesn't `@static` mean that this check executes at lowering time (which happens when the module is precompiled), not at module-loading time?

**Comment by ararslan** [comment]
Ah yeah, you're right.

**Comment by jtravs** [comment]
Any chance we could get a release tagged with this fix in it? I was just bitten by this and wasted quite a lot of time.

**Comment by ararslan** [comment]
I believe I was as well and didn't even realize it. #148

**Pull request merged**
