### PR TITLE
Stop using ANY

### PR DESCRIPTION
**Pull request by andreasnoack**
It is not a thing anymore

### CODE REVIEW

**Comment by ararslan** [comment]
It's not equivalent to `Any` though; I thought it required the new `@nospecialize` macro?

**Comment by andreasnoack** [comment]
I'm not sure but I thought this only made a difference for the arguments of the function and not when used as a type parameter like this. We should probably consult the authorities.

**Comment by giordano** [comment]
Unrelated, the CI logs on nightly are showing dozens of messages like those reported at https://github.com/JuliaLang/julia/pull/22763#issuecomment-315641223 for `SpecialFunctions.jl`, see e.g. https://travis-ci.org/JuliaMath/FFTW.jl/jobs/254462935#L785

**Comment by ararslan** [comment]
@giordano Yeah, FFTW is just a hot mess in general right now.

**Comment by giordano** [comment]
I opened a ticket (#23) as a reminder.

**Comment by JeffBezanson** [comment]
You might need `(::Type{r2rFFTWPlan{$Tr,A,inplace,N}} where A)` for this to match the same methods as before.

**Pull request merged**
