### PR TITLE
Adds version in deploydocs

### PR DESCRIPTION
**Pull request by navidcy**
This is an attempt to deal with #185.

Unfortunately I don't think that I can push a docs preview, even if I set `push_preview = true` inside `deploydocs()` function so I don't have a way to figure out if this indeed deals with #185.

### CODE REVIEW

**Comment by giordano** [comment]
As far as I can see, the issue is that deploy of documentation on a tag is skipped: https://github.com/JuliaMath/FFTW.jl/runs/1871754241?check_suite_focus=true#step:6:84  No idea why that happens though (and not sure this helps, I mean, I've never seen this flag used)

**Comment by navidcy** [comment]
😕

**Comment by navidcy** [comment]
> As far as I can see, the issue is that deploy of documentation on a tag is skipped: https://github.com/JuliaMath/FFTW.jl/runs/1871754241?check_suite_focus=true#step:6:84 No idea why that happens though (and not sure this PR helps, I mean, I've never seen this flag used)

is this related? I've never seen `julia=...` kwarg in `deplaydocs()`....
https://github.com/JuliaMath/FFTW.jl/blob/6ad135ab0be80399156c12b341c70dfbd3429d7f/docs/make.jl#L15

**Comment by giordano** [comment]
That's an old option, I think it isn't needed anymore, but I don't know whether that's the culprit (and I'd find it very bizarre if that was the case).

I have no clue about where the message
```
[ Info: skipping docs deployment.
```
comes from.  Finding it can give us a hint of _why_ deployment is skipped.

**Comment by navidcy** [comment]
Searching `skipping docs deployment` in all of Documenter.jl repo give out nothing! Bizarre.

**Comment by giordano** [comment]
Also, I removed that line in https://github.com/JuliaMath/FFTW.jl/commit/2c20abe7098a2380fa37fe021b3d21fc593059ec

**Comment by navidcy** [comment]
@giordano, if you have write access to the repo then I suggest you create a PR copy of mine, add `push_preview = true` in the `deploydocs` and see if the docs actually deploy.

**Comment by giordano** [comment]
How that would help if the issue is only on tags?

**Comment by navidcy** [comment]
> How that would help if the issue is only on tags?

Oh now I see what you meant above. You are claiming the issue is on *every* tag... (I though you only were trying to say that a particular tag had the issue...)

**Comment by navidcy** [comment]
Although, @giordano, the latest tagged release was with Documenter v0.22.6 and not the later ^0.26... But I have no idea if that's the culprit. Perhaps it's time to ask mortenpi (I'm not tagging them here... I'll let you do that if you think that's in order at this point).

**Comment by giordano** [comment]
I already asked for help on Slack

**Comment by giordano** [comment]
> the latest tagged release was with Documenter v0.22.6

That was a useful reminder, thanks.  I believe the message was coming from https://github.com/JuliaDocs/Documenter.jl/blob/70893ea4c0b17451ff1450a537c2768d226393d3/src/Documenter.jl#L503-L507, but that's already fixed by https://github.com/JuliaMath/FFTW.jl/commit/2c20abe7098a2380fa37fe021b3d21fc593059ec.  So nothing to do, I guess?

**Comment by navidcy** [comment]
Well, there is a way to put back all the non deployed docs. But I’m not sure it worths it. 

https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Documentation-Versions

**Comment by giordano** [comment]
Documentation for v1.3.2 is now available: https://juliamath.github.io/FFTW.jl/v1.3.2/.  I'm going to close this pull request

**Pull request closed without merging**
