### PR TITLE
[WIP] Fix apt-get installation stuff

### PR DESCRIPTION
**Pull request by staticfloat**
Work in progress, simultaneously testing this and the new sudo-less bindeps branch

### CODE REVIEW

**Comment by staticfloat** [comment]
Alright this works on Ubuntu.  I'ma merge it.

**Comment by ararslan** [comment]
Thanks! I'm surprised there isn't a single FFTW package available from APT that provides both single- and double-precision.

**Comment by staticfloat** [comment]
There is, but this is the most minimal way to get what we want.  :)

**Comment by ararslan** [comment]
Sounds great. Thanks again!

**Pull request merged**
