### PR TITLE
Improve inference, bump AbstractFFTs [compat]

### PR DESCRIPTION
**Pull request by timholy**
Companion PR to https://github.com/JuliaMath/AbstractFFTs.jl/pull/48

### CODE REVIEW

**Comment by timholy** [comment]
Looks like the mirrors just haven't updated yet.

**Comment by timholy** [comment]
Closing/opening reran travis but not the others.

**Comment by giordano** [comment]
Related to last comment, #172 is ready for review

**Comment by timholy** [comment]
If we want to merge #172 and then rebase this, that would be fine with me.

**Comment by timholy** [comment]
Are those windwos failures expected?

**Comment by giordano** [comment]
> Are those windows failures expected?

Yes, same as https://github.com/JuliaMath/FFTW.jl/pull/172#issuecomment-751134617.  I might now what's the problem, but didn't have the time to better investigate it yet.

**Pull request merged**
