### PR TITLE
Use relative path for the deps include

### PR DESCRIPTION
**Pull request by musm**
https://github.com/JuliaMath/FFTW.jl/pull/6#discussion_r120142738

### CODE REVIEW

**Comment by ararslan** [comment]
I prefer using the full path but I guess this is fine

**Comment by musm** [comment]
Actually I think we need to revert this.
I was debugging and running issues with ImageMagick and apparently the problem was because I reverted to using relative paths for the deps include file ! was pretty confused and this caused me a bit of grief.

**Comment by musm** [comment]
cc @stevengj

**Comment by stevengj** [comment]
I'm confused by this.  `include` is always relative to the current path, so what possible problems could a relative path cause?

**Comment by stevengj** [comment]
(Functions *other* than `include`, like `open` etcetera, are *not* relative to the current file's path and *do* need to use absolute paths to open files in the package directory.  Maybe that's what you were seeing?)

**Pull request merged**
