### PR TITLE
Revert "Use relative path for the deps include"

### PR DESCRIPTION
**Pull request by musm**
Reverts JuliaMath/FFTW.jl#7

### CODE REVIEW

**Comment by stevengj** [comment]
I'm opposed to this unless we can clearly identify what problem this solves.

**Comment by musm** [comment]
For reference both myself and @Allardvm observed this problem when we did not include the absolute path. We are not exactly sure but the only thing that this file contained was  the library path and dictionary entries.  FWIW this was an issue we observed in windows 

perhaps @tkelman  has seen this in the past

**Comment by stevengj** [comment]
Library paths need to be absolute. Not include paths

**Comment by stevengj** [comment]
(Merging workarounds without diagnosing the problem is a good way to hide bugs/misunderstandings.)

**Comment by tkelman** [comment]
I think it's the `isfile` that can change behavior here, but I forget in what way

**Comment by ararslan** [comment]
We could just use full paths everywhere, since they're guaranteed to work as expected.

**Comment by stevengj** [comment]
Right, isfile is the problem here.

**Comment by musm** [comment]
should a bug report be open to try and fix `ifile` or is that not possible?

**Comment by musm** [comment]
FWIW  I believe the issue we were seeing was related to something else (i.e. I can't seem to trigger the problem with using relative paths with `include`)

I agree using relative paths should just work without having to special case cases like this which I guess can lead to hard to trace bugs

**Comment by stevengj** [comment]
@musm, no, `isfile`, along with all other file operations, is supposed to be relative to the current working directory (`pwd()`), which is *not* necessarily the same as the directory of the current file.

*Only* `include` is supposed to be relative to the directory of the current *file*.

**Pull request merged**
