### PR TITLE
Allow installing MKL_jll 2021

### PR DESCRIPTION
**Pull request by giordano**
This should finally fix the failures on Windows with Julia nightly.

### CODE REVIEW

**Comment by giordano** [comment]
macOS with Julia v1.3 doesn't seem to like it...

**Comment by ianshmean** [comment]
Passes tests locally on MacOS 11.1, julia 1.3.1 & 1.5.3
But errors on nightly
```
julia> ENV["JULIA_FFTW_PROVIDER"]="MKL"
"MKL"

(jl_Ldu9rh) pkg> build FFTW
    Building FFTW → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/c31e446bf3b12aad2ec8fc500fe19528c148d811/build.log`
  Progress [========================================>]  1/1
1 dependency successfully precompiled in 1 seconds (9 already precompiled)

(jl_Ldu9rh) pkg> test FFTW
     Testing FFTW
      Status `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_neyfUu/Project.toml`
  [621f4979] AbstractFFTs v1.0.0
  [7a1cc6ca] FFTW v1.3.1
  [189a3867] Reexport v1.0.0
  [f5851436] FFTW_jll v3.3.9+7
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+1
  [856f044c] MKL_jll v2020.2.254+0
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [8dfed614] Test `@stdlib/Test`
      Status `/private/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_neyfUu/Manifest.toml`
  [621f4979] AbstractFFTs v1.0.0
  [7a1cc6ca] FFTW v1.3.1
  [692b3bcd] JLLWrappers v1.2.0
  [189a3867] Reexport v1.0.0
  [f5851436] FFTW_jll v3.3.9+7
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+1
  [856f044c] MKL_jll v2020.2.254+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [f43a241f] Downloads `@stdlib/Downloads`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
     Testing Running tests...
INTEL MKL ERROR: dlopen(/Users/ian/.julia/artifacts/d294618610458f0427a31d74ecc213d22938e95c/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/ian/.julia/artifacts/d294618610458f0427a31d74ecc213d22938e95c/lib/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.
ERROR: Package FFTW errored during testing (exit code: 2)
```

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/2412 should have fixed the issue with IntelOpenMP on macOS.  All macOS jobs on nightly seems to hang forever when building the package, no idea why, but I think it's unrelated to this PR, since it happens also when the FFTW provider is used.  I'm setting a 10-minute timeout for CI to avoid hanging the jobs for 6 hours

**Comment by stevengj** [comment]
LGTM.

**Review by stevengj — APPROVED** [review]

**Pull request merged**
